name: quotes
description: "Quotes App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.5
  get_it: ^7.7.0
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/quote.png
    - lang/ar.json
    - lang/en.json

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
